name: Ditto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests_with_std_containers:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: ['clang++-14', 'g++']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-D BUILD_DITTO_TESTS=ON -D USE_STD_TEMPLATES=ON -DDITTO_TARGET_ARCH=x86_64'
        buildDirectory: '${{ github.workspace }}/build'
      env:
        CXX: ${{ matrix.compiler }}
    - name: Execute tests
      run: '${{ github.workspace }}/build/DittoTests'

  tests_without_std_containers:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: ['clang++-14', 'g++']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DBUILD_DITTO_TESTS=ON -DDITTO_TARGET_ARCH=x86_64'
        buildDirectory: '${{ github.workspace }}/build'
      env:
        CXX: ${{ matrix.compiler }}
    - name: Execute tests
      run: '${{ github.workspace }}/build/DittoTests'

  clang_format:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        clangFormatVersion: 14
