name: Containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-D BUILD_DITTO_TESTS=ON'
        buildDirectory: '${{ github.workspace }}/build'
      env:
        CC: ${{ matrix.os == 'ubuntu-latest' && 'clang-12' || 'clang' }}
        CXX: ${{ matrix.os == 'ubuntu-latest' && 'clang++-12' || 'clang++' }}
    - name: Execute tests
      run: '${{ github.workspace }}/build/DittoTests'
